version: '2'

services:
  bdocs:
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    command: make -C docs html
  sdocs:
    image: nginx
    ports:
      - '35555:80'
    volumes:
      - ./docs/_build/html:/usr/share/nginx/html
